config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get "/schools/search" => 'schools#search'
  get "schools/getschools" => 'schools#getschools'
  get 'schools/user_input' => "schools#user_input"

end

app/models/school.rb
class School < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  def self.school_search(term, year)
    where('LOWER(name) LIKE :term AND years= :year',
           term: "%#{term.downcase}%", year: year)
  end

  def self.data_prep(inc, schools)
    ids = schools.split(',').map(&:to_i) # "22,33,444" to [22, 33, 444]
    ids.uniq! # removes duplicates
    price = "net_price_" + inc # avg to net_price_avg -column name
    loan = "loan_" + inc
    earn = "earn_" + inc
    self.data_query(ids, price, loan, earn)
  end

  def self.data_query(ids, price, loan, earn)
    schools = []
    ids.each do |id|
      school = School.select("name", "control", "net_price_avg", "#{price} AS price",
                             "loan_avg", "#{loan} AS loan", "earn_avg",
                             "#{earn} AS earn").where(["id = ?", id]).first
      if school.price == 0
         school.price = school.net_price_avg
      end
      if school.loan == 0
        school.loan = school.loan_avg
      end
      if school.earn == 0
        school.earn = school.earn_avg
      end
      schools << school
    end
    return schools
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController

  def search
    @schools = School.school_search(params[:term], params[:years])

    respond_to do |format|
      format.html
      format.json { render json: @schools.select('id', 'name', 'state', 'url') }
    end
  end

  def getschools
    schools = School.data_prep(params["inc"], params["school-ids"])
    begin
      data = schools
      code = :ok
    rescue
      data = {}
      code = :no_content
    end
    render json: data.as_json, code: code
  end
end

app/views/home/index.html.erb
<div class="container-fluid">

  <div class="page-header">
    <div class="row">
      <i class="fa fa-info fa-3x" data-toggle="modal" data-target="#aboutModal"></i>
    </div>
    <div class="row">
      <div class="col-md-10 col-md-offset-2 title-text">
        <h1><img alt="Mortarboard" src="/assets/mortarboard-b63218e73eb750efed0b7bd95d65da009156a58f415f6fa5498f45ebc84088ad.svg" width="65" height="65">  College Cost Comparator <br/><small> Discover your average cost, debt, and earnings from schools nationwide!</small></h1>
        <%= button_tag "Start Over", class: "btn btn-secondary start-over" %>
      </div>
    </div>
  </div>

<div class="row page-content">
  <div class=search-form>
    <%= form_tag(schools_user_input_path, method: :get, role: "user_input") do %>
    <div class="col-md-5 user-selections">
        <h4> Choose your annual family income level: </h4>
          <input id="low_income" name="inc" type="radio" value="low" />
          <label for="low_income">Low-Income ($0-48k)</label>
        <br>
          <input id="mid_income" name="inc" type="radio" value="mid" />
          <label for="mid_income">Mid-Income ($30-75k)</label>
        <br>
          <input id="high_income" name="inc" type="radio" value="high" />
          <label for="high_income">High-Income ($75k+)</label>
        <br>
          <input checked="checked" id="avg_income" name="inc" type="radio" value="avg" />
          <label for="avg_income">Don't know/Prefer not to answer</label>
        <br>
        <input name="school-ids" id="school-ids" type="hidden" value="" />
      </div>
      <div class="col-md-7">
        <h4> Choose schools to compare: </h4>
          <input id="two_year" name="years" type="radio" value="2" />
          <label for="two_year">Two-Year Schools</label>
          <input checked="checked" id="four_year" name="years" type="radio" value="4" />
          <label for="four_year">Four-Year Schools</label>
        <section class="app-content">
          <div class="school-search">
            <input type="text" id="school-search-txt" placeholder="Type school here..."/>
            <div class="results" id="school-search-results"></div>
          </div>
          <div id="selected-schools">
            <h4>Selected schools:</h4>
            <p class="no-data"> No schools selected.</p>
          </div>
        </section>
      <%= button_tag "Compare Schools", class: "btn btn-secondary btn-lg user-input" %>
      </div>
    <% end %>
  </div>
</div>
<hr>

<div class="row">
  <div id="switch-buttons" class="hidden-xs-up">
    <p> Hover over bars to interact with the data!</p>
    <%= button_tag "Net Price", class: "price-switch btn btn-primary" %>
    <%= button_tag "Earnings", class: "earn-switch btn btn-success" %>
    <%= button_tag "Loans", class: "loan-switch btn btn-danger" %>
    <i class='fa fa-sort fa-2x' data-toggle="tooltip" data-placement="right" title="Click to sort"></i>
  </div>
  <svg class="bar-chart col-xs-12"></svg>
</div>

<div id="tooltip" class="hidden-xs-up">
  <p><span id="value"></span></p>
</div>
<div class="cylinder-chart">
  <svg class="cyl-chart col-xs-12"></svg>
</div>

<!-- Modal -->
  <div class="modal fade" id="aboutModal" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">x</button>
          <h2 class="modal-title">About this Project</h2>
        </div>
        <div class="modal-body">
          <h3>Developer</h3>
          <p>This is <a target="_blank" href="http://eliamg.com/">Elia Grenier's</a> capstone project for <a target="_blank" href="http://adadevelopersacademy.org">Ada Developer's Academy</a> in Seattle, WA.</p>
          <h3>Dataset</h3>
          <p>The data used in this project is provided by the most recent <a target="_blank" href="https://collegescorecard.ed.gov">federal College Scorecard</a> dataset. Schools listed were filtered to only include two and four year undergraduate serving schools (per Carnegie classification) with net price, loan and earnings data available.</p>
          <h3>Definitions</h3>
          <h4>Why Earnings minus Loans?</h4>
            <p>A good rule of thumb is to keep total loan debt less than you expect to earn as an initial starting salary.</p>
          <h4>Net Price </h4>
            <p> Full cost of attendance (including tuition and fees, books and supplies, and living expenses) minus federal, state, and institutional aid, for undergraduate Title IV-receiving students. For public institutions, this metric is limited to undergraduates who pay in-state tuition. </p>
          <h4>Loan Debt</h4>
            <p> The median loan debt accumulated at the institution by all student borrowers of federal loans who separate (i.e., either graduate or withdraw) in a given year. </p>
          <h4>Earnings</h4>
            <p> Mean earnings are for all federally aided students who enroll in an institution each year and who are employed but not enrolled 6 years after the student enrolleed in the institution. Earnings are calculated from students' W-2 and self-employment filing and are privacy suppressed when the number of students in the mean calculation is too low. </p>
            <p><small>Mortar Board by Anders Seierøe Mortensen from the Noun Project</p>
        </div>
      </div>
    </div>
  </div>
 <i id="back-to-top" class="fa fa-chevron-up fa-2x"></i>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='https://fonts.googleapis.com/css?family=Ubuntu:400,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <meta name="viewport" content="width=device-width", initial-scale="1.0">
  <title>College Cost Comparator</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>